language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev liblapack-dev gfortran
    - sudo apt-get install -qq libpng12-dev libtiff4-dev libwebp-dev
    - sudo apt-get install -qq xcftools
install:
    - pip install numpy
    - make debug
script: nosetests
